# Event type is issues and opened.
# If your opened issues has title/lables with any word of bug.
# It will give output "Issue about a bug"
# Otherwise it will give output "Issue doesn't about a bug"

name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        # env:
        #   TITLE: ${{ github.event.issue.title }}
        # run: |
        #   issue_title="${{ github.event.issue.title }}"
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
        
      # if youe issuwes title like this, a";echo Get your Secrets"
      # title may only of "a" -- ";" next line , echo -- print.
      # If you type a";echo $AWS_ACCESS_KEY" -- It will really print your aws cred.
      # Which is bot prederable.
      # To avoid that bad event,, store your cred as env.

# 2nd Way
# use your run: | code in your custom actions repo and call workflow bt workflow_call.