# Event type is issues and opened.
# If your opened issues has title/lables with any word of bug.
# It will give output "Issue about a bug"
# Otherwise it will give output "Issue doesn't about a bug"

name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi